"""Codes to descriptors and descriptor hierarchy

Revision ID: 287aee0262ca
Revises: 339f3cd6e2af
Create Date: 2014-02-28 12:30:54.079864

"""

# revision identifiers, used by Alembic.
revision = '287aee0262ca'
down_revision = '339f3cd6e2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptor', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('descriptor', sa.Column('parent_code', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descriptor', 'parent_code')
    op.drop_column('descriptor', 'code')
    ### end Alembic commands ###
