"""Nullable names

Revision ID: 339f3cd6e2af
Revises: 1ee1e1f6aaf3
Create Date: 2014-02-28 12:19:08.967090

"""

# revision identifiers, used by Alembic.
revision = '339f3cd6e2af'
down_revision = '1ee1e1f6aaf3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'first_name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('person', 'first_surname',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('person', 'second_surname',
               existing_type=mysql.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'second_surname',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('person', 'first_surname',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('person', 'first_name',
               existing_type=mysql.TEXT(),
               nullable=False)
    ### end Alembic commands ###
