"""University location

Revision ID: 4eb0d0716ca0
Revises: 287aee0262ca
Create Date: 2014-02-28 12:32:53.413430

"""

# revision identifiers, used by Alembic.
revision = '4eb0d0716ca0'
down_revision = '287aee0262ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('location', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'location')
    ### end Alembic commands ###
